<?php
// $Id$

/**
 * @file
 * Receives and parses XML sent from a Flash app via URL POST request.
 * 
 */

/**
 * Implementation of hook_menu().
 */
function flash_data_menu() {
	
	$items = array();
	$items['flash_input'] = array(
		'title' => t('Testing'),
		'page callback' => 'flash_data_receive',
		'access arguments' => array(TRUE),
		'type' => MENU_CALLBACK
	);
	
	return $items;
}

/**
 * Parse XML posted via URL REQUEST POST
 *
 * XML sent can trigger the following options:
 * - Send Achievement
 * - Send Document
 * - Send Research
 * - Send Forum
 * - Send Checkpoint
 */
function flash_data_receive() {
  
	$xml = file_get_contents('php://input');
  $xml = check_markup($xml, 5);
	$data = xml_parser_string_to_array($xml);
	
	// Gather generic data
	$player_id = $data["PLAYERID"];
	$game_id = $data["GAMEID"];
	
	$achievement_id = $data["achievement"]["ACHIEVEMENTID"];
	$document_id = $data["document"]["DOCUMENTID"];
	$checkpoint = $data["checkpoint"];
	$forum_id = $data["forum"]["THREADID"];
	$research = $data["research"];
	
	// Prepare string for view
	$output = 'Player ID: ' . $player_id . "\n";
	$output .= 'Game ID: ' . $game_id . "\n";
	if($achievement_id) {
	  $output .= 'Achievement ID: ' . $achievement_id . "\n";
	}
	if($document_id) {
		$output .= 'Document ID: ' . $document_id . "\n";
	}
	if($checkpoint) {
		$output .= 'Checkpoint: ' . $checkpoint . "\n";
	}
	if($forum_id) {
		$output .= 'Forum ID: ' . $forum_id . "\n";
		$output .= 'Forum message: ' . $forum_message . "\n";
	}
	if($research) {
		$output .= 'Research: ' . $research . "\n";
	}
	
	// Create a Flash Data node
	$node = new stdClass();
  $node->title = $game_id . ': ' . date('Y-m-d H:i:s');
  $node->body = $output;
  $node->type = 'flash_data';
  $node->status = 1;
  $node->format = 1;
  node_save($node);
	
  // dpr($data);
  // dpr($player_id . ", " . $game_id . ", " . $achievement_id);
}


/**
 * Implementation of hook_nodeapi
 * 
 * Handles updating the flashvars for Flash content type nodes
 */
function flash_data_nodeapi(&$node, $op) {
	if($op == "load" && $node->type == "flashnode") {
		
		global $base_url;
		global $user;
		
		$checkpoint = '29898234';
		$url = $base_url . '/flash_input';
		$player = $user->uid;
		$node->flashnode['flashvars'] = t('checkpoint=@checkpoint&playerId=@player&gameId=@game&post=@url', array('@checkpoint' => $checkpoint, '@player' => $player, '@game' => $node->title, '@url' => $url));
	}
}




